if (window.AuthGuard) {
  window.AuthGuard.protectAdminPage();
}
const db = supabase.createClient('https://aknhxrhlahusgfpiknau.supabase.co','sb_publishable_BFsu6iC-nWsKfdKQgoXimQ_dNmbgxTj');
const paymentMonth = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`; };
const input=document.querySelector('#studentIdInput'), info=document.querySelector('#studentInfo'), message=document.querySelector('#message');
let current=null, busy=false, scanner;
const show=(text,type='error')=>{message.textContent=text;message.className=`message ${type}`};
const reset=()=>{info.classList.add('hidden');current=null;input.value='';input.focus();try{scanner?.resume()}catch{}};
const beep=()=>{try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);g.gain.value=.08;o.frequency.value=800;o.start();o.stop(c.currentTime+.12)}catch{}};
const studentCode=value=>{try{return new URL(value).searchParams.get('code')||value.trim()}catch{return value.trim()}};
async function findStudent(){const code=studentCode(input.value);if(!code)return show('امسح QR Code أو أدخل رقم الطالب.');message.className='message hidden';const {data:s,error}=await db.from('students').select('*').eq('student_id',code).maybeSingle();if(error||!s){info.classList.add('hidden');return show('الطالب غير موجود في قاعدة البيانات.')}const {data:p}=await db.from('payments').select('*').eq('student_id',s.id).eq('payment_month',paymentMonth()).maybeSingle();current={...s,status:p?.status||'غير مدفوع'};document.querySelector('#portalLink').href=`student-portal.html?code=${encodeURIComponent(s.student_id)}`;document.querySelector('#studentName').textContent=s.student_name;document.querySelector('#studentId').textContent=s.student_id;document.querySelector('#studentGroup').textContent=s.student_group;const paid=current.status==='مدفوع', pay=document.querySelector('#paymentStatusText'),payBtn=document.querySelector('#payAndAttendBtn');pay.textContent=paid?'مدفوع ✅':'غير مدفوع ❌';pay.className=paid?'payment-paid':'payment-unpaid';payBtn.disabled=paid;payBtn.textContent=paid?'💳 مدفوع بالفعل':'💳 دفع وتسجيل حضور';info.classList.remove('hidden')}
async function complete(withPayment){if(!current||busy)return;busy=true;document.querySelectorAll('.actions button').forEach(b=>b.disabled=true);try{let status=current.status;if(withPayment){const {error}=await db.from('payments').upsert({student_id:current.id,payment_month:paymentMonth(),status:'مدفوع',paid_at:new Date().toISOString()},{onConflict:'student_id,payment_month'});if(error)throw error;status='مدفوع'}const {error}=await db.from('attendance').insert({student_id:current.id,payment_status:status});if(error)throw error;reset();show('تم تسجيل الحضور بنجاح ✅','ok')}catch(e){show(e.code==='23505'?'تم تسجيل حضور هذا الطالب اليوم بالفعل!':e.message||'حدث خطأ أثناء تنفيذ العملية.')}finally{busy=false;document.querySelectorAll('.actions button').forEach(b=>b.disabled=false)}}
async function clearAll(){if(!confirm('هل تريد مسح كل سجلات الحضور؟ لن تتأثر بيانات الطلاب أو المدفوعات.'))return;const {error}=await db.from('attendance').delete().neq('id','00000000-0000-0000-0000-000000000000');if(error)return show(error.message);reset();show('تم بدء يوم جديد ومسح سجل الحضور.','ok')}
window.addEventListener('DOMContentLoaded',()=>{document.querySelector('#currentMonthLabel').textContent=new Intl.DateTimeFormat('ar-EG',{month:'long'}).format(new Date());document.querySelector('#scanBtn').onclick=findStudent;input.onkeydown=e=>e.key==='Enter'&&findStudent();document.querySelector('#attendanceOnlyBtn').onclick=()=>complete(false);document.querySelector('#payAndAttendBtn').onclick=()=>complete(true);document.querySelector('#clearAttendanceBtn').onclick=clearAll;scanner=new Html5Qrcode('qrReader');scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:230,height:230}},text=>{scanner.pause(true);beep();input.value=text.trim();findStudent()},()=>{}).catch(()=>show('اسمح للمتصفح باستخدام الكاميرا لمسح QR Code.'))});
