if (window.AuthGuard) {
  window.AuthGuard.protectAdminPage();
}
const db=supabase.createClient('https://aknhxrhlahusgfpiknau.supabase.co','sb_publishable_BFsu6iC-nWsKfdKQgoXimQ_dNmbgxTj');
const groups=['س ث 1:30','س ث 5','ح ع 12','ح ع 3','ث خ 1:30','ث خ 3','ث خ 5','ث خ 6:30'];let scanner;
const input=document.querySelector('#searchInput'),section=document.querySelector('#editSection');
async function find(value=input.value.trim()){if(!value)return alert('يرجى كتابة كود أو اسم الطالب أو مسح QR.');const {data,error}=await db.from('students').select('*').or(`student_id.eq.${value},student_name.ilike.%${value}%`).limit(1);if(error)return alert(error.message);if(!data?.length){section.classList.add('hidden');return alert('لم يتم العثور على طالب.')}const s=data[0];document.querySelector('#editRowId').value=s.id;document.querySelector('#editStudentCode').value=s.student_id;document.querySelector('#editStudentName').value=s.student_name;document.querySelector('#editStudentGroup').value=s.student_group||'';section.classList.remove('hidden')}
async function save(e){e.preventDefault();const id=document.querySelector('#editRowId').value,student_id=document.querySelector('#editStudentCode').value.trim(),student_name=document.querySelector('#editStudentName').value.trim(),student_group=document.querySelector('#editStudentGroup').value;if(!student_id||!student_name)return alert('يرجى كتابة كود واسم الطالب.');const {error}=await db.from('students').update({student_id,student_name,student_group}).eq('id',id);if(error)return alert(error.message);alert('تم تعديل بيانات الطالب بنجاح ✅');section.classList.add('hidden');input.value=''}
window.addEventListener('DOMContentLoaded',()=>{document.querySelector('#editStudentGroup').innerHTML='<option value="">-- اختر المجموعة --</option>'+groups.map(g=>`<option>${g}</option>`).join('');document.querySelector('#searchBtn').onclick=()=>find();input.onkeydown=e=>e.key==='Enter'&&find();document.querySelector('#editForm').onsubmit=save;const q=new URLSearchParams(location.search).get('q');if(q){input.value=q;find(q)}scanner=new Html5Qrcode('qrReader');scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:220,height:220}},text=>{scanner.pause(true);input.value=text.trim();find()},()=>{}).catch(()=>{})});
