if (window.AuthGuard) {
  window.AuthGuard.protectAdminPage();
}
const db = supabase.createClient('https://aknhxrhlahusgfpiknau.supabase.co','sb_publishable_BFsu6iC-nWsKfdKQgoXimQ_dNmbgxTj');
const paymentMonth = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`; };
const GROUPS = ['س ث 1:30','س ث 5','ح ع 12','ح ع 3','ث خ 1:30','ث خ 3','ث خ 5','ث خ 6:30'];
let students=[];const groups=()=>GROUPS.map(x=>`<option value="${x}">${x}</option>`).join('');
const nextCode=list=>{const max=list.reduce((m,s)=>Math.max(m,Number((s.student_id||'').replace('STUD-',''))||0),0);return `STUD-${String(max+1).padStart(3,'0')}`};
async function load(){const {data,error}=await db.from('students').select('*').order('created_at',{ascending:false});if(error)return alert('خطأ في جلب الطلاب: '+error.message);students=data||[];document.querySelector('#newStudentId').value=nextCode(students);render()}
function render(){const q=document.querySelector('#searchInput').value.trim().toLowerCase(),body=document.querySelector('#studentsTableBody');if(!q){body.innerHTML='<tr><td colspan="4" class="empty">🔍 اكتب اسم الطالب أو الكود للبحث.</td></tr>';return}const result=students.filter(s=>(s.student_id||'').toLowerCase().includes(q)||(s.student_name||'').toLowerCase().includes(q));body.innerHTML=result.length?result.map(s=>`<tr><td><b>${s.student_id}</b></td><td>${s.student_name}</td><td>${s.student_group}</td><td><a class="btn primary tiny" href="edit_student.html?q=${encodeURIComponent(s.student_id)}">تعديل ✏️</a> <button class="btn danger tiny" data-id="${s.id}" data-name="${s.student_name}">حذف 🗑️</button></td></tr>`).join(''):'<tr><td colspan="4" class="empty">لا يوجد طالب مطابق.</td></tr>';body.querySelectorAll('button').forEach(b=>b.onclick=()=>remove(b.dataset.id,b.dataset.name))}
async function remove(id,name){if(!confirm(`هل أنت متأكد من حذف الطالب (${name})؟`))return;const {error}=await db.from('students').delete().eq('id',id);if(error)return alert(error.message);load()}
async function add(e){e.preventDefault();const student_id=document.querySelector('#newStudentId').value,student_name=document.querySelector('#newStudentName').value.trim(),student_group=document.querySelector('#newStudentGroup').value;if(!student_name||!student_group)return;const {error}=await db.from('students').insert({student_id,student_name,student_group});if(error)return alert('فشل الإضافة: '+error.message);e.target.reset();alert('تمت إضافة الطالب بنجاح ✅');load()}
const file=(data,name,sheet)=>{const w=XLSX.utils.json_to_sheet(data),b=XLSX.utils.book_new();XLSX.utils.book_append_sheet(b,w,sheet);XLSX.writeFile(b,name)};
async function exportNew(){const start=new Date();start.setHours(0,0,0,0);const {data,error}=await db.from('students').select('*').gte('created_at',start.toISOString()).order('created_at',{ascending:false});if(error)return alert(error.message);if(!data?.length)return alert('لا يوجد طلاب جدد اليوم.');file(data.map(s=>({'كود الطالب (QR Code)':s.student_id,'اسم الطالب':s.student_name,'المجموعة':s.student_group,'تاريخ الإضافة':new Date(s.created_at).toLocaleDateString('ar-EG')})),`الطلاب_الجدد_QR_${new Date().toISOString().slice(0,10)}.xlsx`,'الطلاب الجدد')}
async function exportAll(){const [{data:all,error:a},{data:pays,error:b}]=await Promise.all([db.from('students').select('*').order('student_id'),db.from('payments').select('*').eq('payment_month',paymentMonth())]);if(a||b)return alert((a||b).message);const paid=new Set(pays.filter(p=>p.status==='مدفوع').map(p=>p.student_id));file(all.map(s=>({'كود الطالب':s.student_id,'اسم الطالب':s.student_name,'المجموعة':s.student_group,'حالة الدفع للشهر الحالي':paid.has(s.id)?'مدفوع ✅':'غير مدفوع ❌'})),`تقرير_الطلاب_${paymentMonth()}.xlsx`,'كل الطلاب')}
window.addEventListener('DOMContentLoaded',()=>{document.querySelector('#newStudentGroup').innerHTML='<option value="">-- اختر المجموعة --</option>'+groups();document.querySelector('#addStudentForm').onsubmit=add;document.querySelector('#searchInput').oninput=render;document.querySelector('#exportNewQrBtn').onclick=exportNew;document.querySelector('#exportAllStudentsBtn').onclick=exportAll;load()});
